package com.roona;
// Generated Jan 26, 2016 12:16:59 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name = "application", catalog = "myworkflowapp")
public class Application implements java.io.Serializable {

	private int id;
	private String version;
	private String name;
	private String licensed;
	private Applicationstatus applicationstatus;

	public Application() {
	}

	public Application(int id) {
		this.id = id;
	}

	public Application(int id, String name, String licensed, Applicationstatus applicationstatus) {
		this.id = id;
		this.name = name;
		this.licensed = licensed;
		this.applicationstatus = applicationstatus;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", length = 45)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "licensed", length = 45)
	public String getLicensed() {
		return this.licensed;
	}

	public void setLicensed(String licensed) {
		this.licensed = licensed;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "application")
	public Applicationstatus getApplicationstatus() {
		return this.applicationstatus;
	}

	public void setApplicationstatus(Applicationstatus applicationstatus) {
		this.applicationstatus = applicationstatus;
	}

}
