package com.roona;
// Generated Jan 26, 2016 12:16:59 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Applicationstatus generated by hbm2java
 */
@Entity
@Table(name = "applicationstatus", catalog = "myworkflowapp")
public class Applicationstatus implements java.io.Serializable {

	private int applicationid;
	private Application application;
	private String assignedto;
	private String assigneddate;
	private String dstartdate;
	private String denddate;
	private String qstartdate;
	private String qenddate;
	private String pistartdate;
	private String pienddate;
	private String pdate;

	public Applicationstatus() {
	}

	public Applicationstatus(Application application) {
		this.application = application;
	}

	public Applicationstatus(Application application, String assignedto, String assigneddate, String dstartdate,
			String denddate, String qstartdate, String qenddate, String pistartdate, String pienddate, String pdate) {
		this.application = application;
		this.assignedto = assignedto;
		this.assigneddate = assigneddate;
		this.dstartdate = dstartdate;
		this.denddate = denddate;
		this.qstartdate = qstartdate;
		this.qenddate = qenddate;
		this.pistartdate = pistartdate;
		this.pienddate = pienddate;
		this.pdate = pdate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "application") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "applicationid", unique = true, nullable = false)
	public int getApplicationid() {
		return this.applicationid;
	}

	public void setApplicationid(int applicationid) {
		this.applicationid = applicationid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	@Column(name = "assignedto", length = 45)
	public String getAssignedto() {
		return this.assignedto;
	}

	public void setAssignedto(String assignedto) {
		this.assignedto = assignedto;
	}

	@Column(name = "assigneddate", length = 45)
	public String getAssigneddate() {
		return this.assigneddate;
	}

	public void setAssigneddate(String assigneddate) {
		this.assigneddate = assigneddate;
	}

	@Column(name = "dstartdate", length = 45)
	public String getDstartdate() {
		return this.dstartdate;
	}

	public void setDstartdate(String dstartdate) {
		this.dstartdate = dstartdate;
	}

	@Column(name = "denddate", length = 45)
	public String getDenddate() {
		return this.denddate;
	}

	public void setDenddate(String denddate) {
		this.denddate = denddate;
	}

	@Column(name = "qstartdate", length = 45)
	public String getQstartdate() {
		return this.qstartdate;
	}

	public void setQstartdate(String qstartdate) {
		this.qstartdate = qstartdate;
	}

	@Column(name = "qenddate", length = 45)
	public String getQenddate() {
		return this.qenddate;
	}

	public void setQenddate(String qenddate) {
		this.qenddate = qenddate;
	}

	@Column(name = "pistartdate", length = 45)
	public String getPistartdate() {
		return this.pistartdate;
	}

	public void setPistartdate(String pistartdate) {
		this.pistartdate = pistartdate;
	}

	@Column(name = "pienddate", length = 45)
	public String getPienddate() {
		return this.pienddate;
	}

	public void setPienddate(String pienddate) {
		this.pienddate = pienddate;
	}

	@Column(name = "pdate", length = 45)
	public String getPdate() {
		return this.pdate;
	}

	public void setPdate(String pdate) {
		this.pdate = pdate;
	}

}
