package com.roona;
// Generated Jan 26, 2016 12:16:59 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Complexity generated by hbm2java
 */
@Entity
@Table(name = "complexity", catalog = "myworkflowapp")
public class Complexity implements java.io.Serializable {

	private int id;
	private String complexity;

	public Complexity() {
	}

	public Complexity(int id) {
		this.id = id;
	}

	public Complexity(int id, String complexity) {
		this.id = id;
		this.complexity = complexity;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "complexity", length = 45)
	public String getComplexity() {
		return this.complexity;
	}

	public void setComplexity(String complexity) {
		this.complexity = complexity;
	}

}
