package com.roona;
// Generated Jan 26, 2016 12:16:59 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "myworkflowapp")
public class Status implements java.io.Serializable {

	private int id;
	private String status;

	public Status() {
	}

	public Status(int id) {
		this.id = id;
	}

	public Status(int id, String status) {
		this.id = id;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
