package com.roona;
// Generated Jan 25, 2016 11:19:41 PM by Hibernate Tools 4.3.1.Final

/**
 * Applicationstatus generated by hbm2java
 */
public class Applicationstatus implements java.io.Serializable {

	private int applicationid;
	private Application application;
	private String assignedto;
	private String assigneddate;
	private String dstartdate;
	private String denddate;
	private String qstartdate;
	private String qenddate;
	private String pistartdate;
	private String pienddate;
	private String pdate;

	public Applicationstatus() {
	}

	public Applicationstatus(Application application) {
		this.application = application;
	}

	public Applicationstatus(Application application, String assignedto, String assigneddate, String dstartdate,
			String denddate, String qstartdate, String qenddate, String pistartdate, String pienddate, String pdate) {
		this.application = application;
		this.assignedto = assignedto;
		this.assigneddate = assigneddate;
		this.dstartdate = dstartdate;
		this.denddate = denddate;
		this.qstartdate = qstartdate;
		this.qenddate = qenddate;
		this.pistartdate = pistartdate;
		this.pienddate = pienddate;
		this.pdate = pdate;
	}

	public int getApplicationid() {
		return this.applicationid;
	}

	public void setApplicationid(int applicationid) {
		this.applicationid = applicationid;
	}

	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	public String getAssignedto() {
		return this.assignedto;
	}

	public void setAssignedto(String assignedto) {
		this.assignedto = assignedto;
	}

	public String getAssigneddate() {
		return this.assigneddate;
	}

	public void setAssigneddate(String assigneddate) {
		this.assigneddate = assigneddate;
	}

	public String getDstartdate() {
		return this.dstartdate;
	}

	public void setDstartdate(String dstartdate) {
		this.dstartdate = dstartdate;
	}

	public String getDenddate() {
		return this.denddate;
	}

	public void setDenddate(String denddate) {
		this.denddate = denddate;
	}

	public String getQstartdate() {
		return this.qstartdate;
	}

	public void setQstartdate(String qstartdate) {
		this.qstartdate = qstartdate;
	}

	public String getQenddate() {
		return this.qenddate;
	}

	public void setQenddate(String qenddate) {
		this.qenddate = qenddate;
	}

	public String getPistartdate() {
		return this.pistartdate;
	}

	public void setPistartdate(String pistartdate) {
		this.pistartdate = pistartdate;
	}

	public String getPienddate() {
		return this.pienddate;
	}

	public void setPienddate(String pienddate) {
		this.pienddate = pienddate;
	}

	public String getPdate() {
		return this.pdate;
	}

	public void setPdate(String pdate) {
		this.pdate = pdate;
	}

}
