package com.roona;
// Generated Jan 25, 2016 11:19:41 PM by Hibernate Tools 4.3.1.Final

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	private int id;
	private String version;
	private String name;
	private String licensed;
	private Applicationstatus applicationstatus;

	public Application() {
	}

	public Application(int id) {
		this.id = id;
	}

	public Application(int id, String name, String licensed, Applicationstatus applicationstatus) {
		this.id = id;
		this.name = name;
		this.licensed = licensed;
		this.applicationstatus = applicationstatus;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLicensed() {
		return this.licensed;
	}

	public void setLicensed(String licensed) {
		this.licensed = licensed;
	}

	public Applicationstatus getApplicationstatus() {
		return this.applicationstatus;
	}

	public void setApplicationstatus(Applicationstatus applicationstatus) {
		this.applicationstatus = applicationstatus;
	}

}
