package com.roona;
// Generated Jan 25, 2016 11:19:41 PM by Hibernate Tools 4.3.1.Final

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private int id;
	private String status;

	public Status() {
	}

	public Status(int id) {
		this.id = id;
	}

	public Status(int id, String status) {
		this.id = id;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
