-- MySQL Script generated by MySQL Workbench
-- 01/28/16 22:55:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mywebapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mywebapp` ;

-- -----------------------------------------------------
-- Schema mywebapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mywebapp` DEFAULT CHARACTER SET utf8 ;
USE `mywebapp` ;

-- -----------------------------------------------------
-- Table `mywebapp`.`application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mywebapp`.`application` ;

CREATE TABLE IF NOT EXISTS `mywebapp`.`application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `application_version` VARCHAR(45) NULL,
  `islicensed` TINYINT(1) NULL,
  `vendor_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywebapp`.`complexity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mywebapp`.`complexity` ;

CREATE TABLE IF NOT EXISTS `mywebapp`.`complexity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `complexity` VARCHAR(45) NOT NULL COMMENT 'simple/medium/complex',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `complexity_UNIQUE` (`complexity` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywebapp`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mywebapp`.`role` ;

CREATE TABLE IF NOT EXISTS `mywebapp`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL COMMENT 'admin/user/developer',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`role_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywebapp`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mywebapp`.`user` ;

CREATE TABLE IF NOT EXISTS `mywebapp`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `contactno` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `roleid` INT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `role_idx` (`roleid` ASC),
  CONSTRAINT `role`
    FOREIGN KEY (`roleid`)
    REFERENCES `mywebapp`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywebapp`.`application_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mywebapp`.`application_request` ;

CREATE TABLE IF NOT EXISTS `mywebapp`.`application_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `complexity_id` INT NULL,
  `status` VARCHAR(45) NOT NULL,
  `application_id` INT NOT NULL,
  `requestorid` INT NOT NULL,
  `comments` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `complexity_idx` (`complexity_id` ASC),
  INDEX `appid_idx` (`application_id` ASC),
  INDEX `fk_requestor_idx` (`requestorid` ASC),
  CONSTRAINT `fk_application_id`
    FOREIGN KEY (`application_id`)
    REFERENCES `mywebapp`.`application` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_complexity_id`
    FOREIGN KEY (`complexity_id`)
    REFERENCES `mywebapp`.`complexity` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_requestor_id`
    FOREIGN KEY (`requestorid`)
    REFERENCES `mywebapp`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywebapp`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mywebapp`.`team` ;

CREATE TABLE IF NOT EXISTS `mywebapp`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(45) NOT NULL COMMENT 'dev/qa/pilot',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `team_UNIQUE` (`team_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywebapp`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mywebapp`.`address` ;

CREATE TABLE IF NOT EXISTS `mywebapp`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `adress1` VARCHAR(45) NOT NULL,
  `address2` VARCHAR(45) NULL,
  `address3` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NULL,
  `address_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mywebapp`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mywebapp`.`application_request_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mywebapp`.`application_request_details` ;

CREATE TABLE IF NOT EXISTS `mywebapp`.`application_request_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `applicationrequestid` INT NOT NULL,
  `teamid` INT NULL COMMENT 'dev,qa,pilot,prod',
  `assignedto` INT NULL COMMENT 'dev user/qauser/ pilot user',
  `startdate` DATE NULL,
  `enddate` DATE NULL,
  `status` VARCHAR(45) NULL COMMENT 'assigned/inprogress/completed',
  `comments` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_applicationrequest_id_idx` (`applicationrequestid` ASC),
  INDEX `fk_team_id_idx` (`teamid` ASC),
  INDEX `fk_assigned_id_idx` (`assignedto` ASC),
  CONSTRAINT `fk_applicationrequest_id`
    FOREIGN KEY (`applicationrequestid`)
    REFERENCES `mywebapp`.`application_request` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_team_id`
    FOREIGN KEY (`teamid`)
    REFERENCES `mywebapp`.`team` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assigned_id`
    FOREIGN KEY (`assignedto`)
    REFERENCES `mywebapp`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
