package com.roona.dao;
// Generated Feb 27, 2016 12:30:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "mywebapp")
public class Address implements java.io.Serializable {

	private Integer id;
	private User user;
	private String adress1;
	private String address2;
	private String address3;
	private String postcode;
	private String addressType;

	public Address() {
	}

	public Address(User user, String adress1, String addressType) {
		this.user = user;
		this.adress1 = adress1;
		this.addressType = addressType;
	}

	public Address(User user, String adress1, String address2, String address3, String postcode, String addressType) {
		this.user = user;
		this.adress1 = adress1;
		this.address2 = address2;
		this.address3 = address3;
		this.postcode = postcode;
		this.addressType = addressType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "adress1", nullable = false, length = 45)
	public String getAdress1() {
		return this.adress1;
	}

	public void setAdress1(String adress1) {
		this.adress1 = adress1;
	}

	@Column(name = "address2", length = 45)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "address3", length = 45)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "postcode", length = 45)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "address_type", nullable = false, length = 45)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

}
