package com.roona.bo;
// Generated Jan 28, 2016 10:56:05 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Application generated by hbm2java
 */
@Entity
@Table(name = "application", catalog = "mywebapp", uniqueConstraints = @UniqueConstraint(columnNames = "name") )
public class Application implements java.io.Serializable {

	private Integer id;
	private String name;
	private String applicationVersion;
	private Boolean islicensed;
	private String vendorName;
	private Set<ApplicationRequest> applicationRequests = new HashSet<ApplicationRequest>(0);

	public Application() {
	}

	public Application(String name, String applicationVersion, Boolean islicensed, String vendorName,
			Set<ApplicationRequest> applicationRequests) {
		this.name = name;
		this.applicationVersion = applicationVersion;
		this.islicensed = islicensed;
		this.vendorName = vendorName;
		this.applicationRequests = applicationRequests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "application_version", length = 45)
	public String getApplicationVersion() {
		return this.applicationVersion;
	}

	public void setApplicationVersion(String applicationVersion) {
		this.applicationVersion = applicationVersion;
	}

	@Column(name = "islicensed")
	public Boolean getIslicensed() {
		return this.islicensed;
	}

	public void setIslicensed(Boolean islicensed) {
		this.islicensed = islicensed;
	}

	@Column(name = "vendor_name", length = 45)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "application")
	public Set<ApplicationRequest> getApplicationRequests() {
		return this.applicationRequests;
	}

	public void setApplicationRequests(Set<ApplicationRequest> applicationRequests) {
		this.applicationRequests = applicationRequests;
	}

}
