package com.roona.bo;
// Generated Feb 27, 2016 12:23:07 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Complexity generated by hbm2java
 */
@Entity
@Table(name = "complexity", catalog = "mywebapp", uniqueConstraints = @UniqueConstraint(columnNames = "complexity") )
public class Complexity implements java.io.Serializable {

	private Integer id;
	private String complexity;
	private Set<ApplicationRequest> applicationRequests = new HashSet<ApplicationRequest>(0);

	public Complexity() {
	}

	public Complexity(String complexity) {
		this.complexity = complexity;
	}

	public Complexity(String complexity, Set<ApplicationRequest> applicationRequests) {
		this.complexity = complexity;
		this.applicationRequests = applicationRequests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "complexity", unique = true, nullable = false, length = 45)
	public String getComplexity() {
		return this.complexity;
	}

	public void setComplexity(String complexity) {
		this.complexity = complexity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "complexity")
	public Set<ApplicationRequest> getApplicationRequests() {
		return this.applicationRequests;
	}

	public void setApplicationRequests(Set<ApplicationRequest> applicationRequests) {
		this.applicationRequests = applicationRequests;
	}

}
